# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://ltran17.github.io/nbdev_template/"

git_url = "https://github.com/ltran17/nbdev_template/tree/main/"

def custom_doc_links(name): return None
