# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello']

# Cell
def say_hello(to):
    if to == 'Jimmy McGill':
        return 'S\'all good, man.'
    elif to == 'Jesse Pinkman':
        return 'Yo'
    else:
        return f'Hello {to}!'