# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'HelloSayer']

# Cell
def say_hello(to):
    "`say_hello` to {to}...with a couple of exceptions."
    if to == 'Jimmy McGill':
        return 'S\'all good, man.'
    elif to == 'Jesse Pinkman':
        return 'Yo'
    else:
        return f'Hello {to}!'

# Cell
class HelloSayer:
    "Say hello to `to` using `say_hello`"
    def __init__(self, to): self.to = to

    def say(self):
        "Do the saying with `say`"
        return say_hello(self.to)